### ISSUE TITLE
为什么要使用这个名字呢

### ISSUE THREAD

**Issue by xwartz** [shimohq/react-native-prompt-android#2]
既然 iOS 和 Android 都支持，取这个名字有点怪... 虽然说 react-native-prompt 被人占了

**Comment by magicismight** [comment]
因为`react-native-prompt`被占了，而且这个只是android上Alert.prompt的polyfill，ios端是直接用的AlertIOS.prompt.
没想到其他好的名字，是公司内部项目使用的模块，也就没纠结那么多了
你有好的建议也可以提出来

**Comment by xwartz** [comment]
感觉可以加一个你公司的前缀，例如 `@shimo/eact-native-prompt`

**Comment by magicismight** [comment]
有道理，谢谢了
下个版本的时候就一起改过来

**Comment by xwartz** [comment]
不客气，应该谢谢你的，正在使用这个组件
